jobs:
    sast-semgrep:
        machine: true
        steps:
          - checkout
    
          - run: docker run --rm -v ${PWD}:/src semgrep/semgrep semgrep --config auto --output semgrep-output.json --json || true #Allow failure stage
          
          - store_artifacts: #Store artifacts
              path: bandit-output.json
              destination: trufflehog-artifact
              when: always

workflows:
  version: 2
  django:
    jobs:
      - sast-semgrep
