jobs:
    oast:
        docker:
          - image: node:alpine3.21
        steps:
          - checkout
    
          - run: 
              command: |
                npm install
    			npm audit --json > npm_audit-results.json || true
    
          - store_artifacts:
              path: npm_audit-results.json
              destination: npm-audit-artifact
              when: always

workflows:
  version: 2
  django:
    jobs:
      - oast
