jobs:
    nuclei:
      machine: true
      steps:
        - checkout
  
        - run: |
            docker run --user $(id -u):$(id -g) -w /nuclei -v $(pwd):/nuclei:rw --rm projectdiscovery/nuclei:v3.4.2 -u https://prod-tv39jhe7.lab.practical-devsecops.training -j -o nuclei-output.json
  
        - store_artifacts:
            path: nuclei-output.json
            destination: nuclei-artifact

workflows:
  version: 2
  django:
    jobs:
      - nuclei


