jobs:
  oast:
    docker:
      - image: node:23.11
    steps:
      - checkout
      - run:  |
            npm install
            npm install retire
            retire --severity critical --outputformat json --outputpath retirejs_output.json || true
            ls -al
            pwd
            hostname
      - store_artifacts:
          path: retirejs_output.json
          destination: retirejs-artifact
          when: always 

workflows:
  version: 2
  django:
    jobs:
      - oast:
