jobs:
    oast:
        machine: true
        steps:
            - checkout
            - run: docker run --rm -v $(pwd):/src -w /src hysnsec/dependency-check --scan /src --format json --out odc-output.json  || true
            - store_artifacts:
                path: odc-output.json
                destination: odc-artifact
                when: always

workflows:
  version: 2
  django:
    jobs:
      - oast
