jobs:
    oast:
        docker:
          - image: node:23.11
        steps:
          - checkout
          - run : npm version
          - run : npm install
          - run : npm install retire
          - run : retire --severity critical --outputformat json --outputpath retirejs_output.json
          - store_artifacts:
              path: retirejs_output.json
              destination: retirejs-artifact
              when: always #Whatever the outcome of stage is save the artifact  

workflows:
  version: 2
  django:
    jobs:
      - oast
