jobs:
    oast:
        docker:
          - image: node:23.11
        steps:
          - checkout
          - run:
              command: npm version
         - run:
              command: npm install  
          - store_artifacts:
              path: retirejs-output.json
              destination: retirejs-artifact
              when: always #Whatever the outcome of stage is save the artifact   

workflows:
  version: 2
  django:
    jobs:
      - oast
