jobs:
    secret-scanning:
        machine: true
        steps:
          - checkout
    
          - run: docker run --rm -v $(pwd):/src hysnsec/trufflehog filesystem /src --json > trufflehog-output.json   || true
          
          - store_artifacts:
              path: trufflehog-output.json
              destination: trufflehog-artifact
              when: always

workflows:
  version: 2
  django:
    jobs:
      - secret-scanning
