jobs:
    nuclei:
      machine: true
      steps:
        - checkout
  
        - run: |
            #echo $PROD_URL
            docker run -w /nuclei -v $(pwd):/nuclei:rw --rm projectdiscovery/nuclei:v3.4.2 -u $PROD_URL -j -o nuclei-output.json
  
        - store_artifacts:
            path: nuclei-output.json
            destination: nuclei-artifact

workflows:
  version: 2
  django:
    jobs:
      - nuclei


