jobs:
    sast-bandit:
        machine: true
        steps:
          - checkout
    
          - run: docker run --rm -v $(pwd):/src hysnsec/bandit -r /src -f json -o /src/bandit-output.json || true #Allow failure stage
          
          - store_artifacts:
              path: bandit-output.json
              destination: trufflehog-artifact
              when: always

workflows:
  version: 2
  django:
    jobs:
      - sast-bandit
