jobs:
    oast:
        machine: true
        steps:
            - checkout
            - run: docker run --rm -v $(pwd):/src -w /src hysnsec/dependency-check --scan . -f JSON || true
            - store_artifacts:
                path: dependecy-check-report.json
                destination: odc-artifact
                when: always

workflows:
  version: 2
  django:
    jobs:
      - oast
